# Generated by Django 3.2 on 2022-02-10 13:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=5, verbose_name='Группа возраста')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сontent_answer', models.TextField(verbose_name='Содержание ответа')),
                ('prompt', models.TextField(verbose_name='Подсказка')),
                ('action', models.CharField(blank=True, max_length=50, verbose_name='Дейсвие')),
                ('jump', models.CharField(blank=True, max_length=5, verbose_name='Номер следующего вопроса или пусто ()')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='ramup.age', verbose_name='Возраст')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='ramup.town', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(blank=True, max_length=5)),
                ('telephone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Respondents', to='ramup.telephone', verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=5, verbose_name='Номер вопроса (1; 9.1)')),
                ('сontent_question', models.TextField(verbose_name='Содержание вопроса')),
                ('prompt', models.TextField(verbose_name='Подсказка')),
                ('answers', models.ManyToManyField(blank=True, related_name='questions', to='ramup.Answer', verbose_name='Варианты ответов')),
            ],
        ),
    ]
