# Generated by Django 3.2 on 2022-02-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0003_auto_20220213_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_json',
            field=models.JSONField(default={'an': 'first'}, verbose_name='answers'),
        ),
    ]
