# Generated by Django 3.2 on 2022-02-15 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0006_alter_radiostationsbycity_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostationsbycity',
            name='radioStation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ramup.radiostation'),
        ),
    ]
