# Generated by Django 3.2 on 2022-02-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0007_radiostationsbycity_radiostation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiostationsbycity',
            name='frequency',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Частота'),
        ),
    ]
