# Generated by Django 3.2 on 2022-02-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0008_alter_radiostationsbycity_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='answer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вариан ответа'),
        ),
        migrations.AddField(
            model_name='town',
            name='next_question',
            field=models.CharField(blank=True, max_length=10, verbose_name='Следующий вопрос'),
        ),
    ]
