# Generated by Django 3.2 on 2022-03-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0009_auto_20220219_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashedTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_at', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephons', to='ramup.telephone', verbose_name='Телефон')),
            ],
        ),
    ]
