# Generated by Django 3.2 on 2022-03-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0011_benchmark_quotamonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotamonth',
            name='month_year',
            field=models.DateField(blank=True),
        ),
    ]
