# Generated by Django 3.2 on 2022-03-13 05:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0012_alter_quotamonth_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmark',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=1),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='population',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
