# Generated by Django 3.2 on 2022-03-13 05:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0014_alter_benchmark_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkAgeGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')])),
                ('population', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('age', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarkAgeGenders', to='ramup.age')),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkCityAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('age', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarkCityAges', to='ramup.age')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarkCityAges', to='ramup.town')),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkCityGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')])),
                ('population', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarkCityGenders', to='ramup.town')),
            ],
        ),
        migrations.AlterField(
            model_name='quotamonth',
            name='age',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotaMonths', to='ramup.age'),
        ),
        migrations.AlterField(
            model_name='quotamonth',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotaMonths', to='ramup.town'),
        ),
        migrations.DeleteModel(
            name='Benchmark',
        ),
    ]
