# Generated by Django 3.2 on 2022-03-17 12:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramup', '0015_auto_20220313_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkCityGenderAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_M_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('population_F_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('age', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarkCityGenderAges', to='ramup.age')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarkCityGenderAges', to='ramup.town')),
            ],
        ),
    ]
